version: '2.1'
services:

  redis-vector-db:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
  backend:
    image: ghcr.io/spartee/redis-vss-fashion:v0.2.0
    environment:
      DEPLOYMENT: "dev"
      REDIS_DATA_URL: 'redis://redis-vector-db:6379'
      REDIS_OM_URL: 'redis://redis-vector-db:6379'
      REDIS_HOST: 'redis-vector-db'
      REDIS_PORT: 6379
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      - "redis-vector-db"
